export interface contenido {
    id: number;
    title: string;
    modulo1: string;
    modulo2: string;
    modulo3: string;
    apoyo: string;
}

export const contenidoCursos: contenido[] = [
    {
        id: 1,
        title: "Principios de programación en Python",
        modulo1: "<h3>Módulo 1: Sintaxis básica y tipos de datos</h3><p>Python destaca por una sintaxis limpia y legible. Una variable guarda información en memoria y toma su tipo de forma dinámica:</p><ul><li><strong>Enteros y flotantes:</strong> valores numéricos directos para operaciones matemáticas.</li><li><strong>Cadenas de texto:</strong> secuencias de caracteres declaradas entre comillas simples o dobles.</li><li><strong>Booleanos:</strong> estados de verdad indispensables para validar decisiones lógicas.</li></ul>",
        modulo2: "<h3>Módulo 2: Control de flujo y colecciones</h3><p>El flujo del programa se organiza evaluando condiciones y recorriendo estructuras de datos:</p><ul><li><strong>Condicionales:</strong> ramas lógicas que ejecutan bloques específicos según el resultado de una prueba.</li><li><strong>Bucles:</strong> ciclos estructurados para repetir tareas o procesar elementos uno a uno.</li><li><strong>Listas y diccionarios:</strong> colecciones clave para ordenar elementos secuenciales o asociar pares de clave y valor.</li></ul>",
        modulo3: "<h3>Módulo 3: Funciones y scripts funcionales</h3><p>Modularizar el código facilita la depuración y evita escribir tareas repetitivas:</p><ul><li><strong>Declaración de funciones:</strong> bloques reutilizables que aceptan parámetros de entrada y retornan resultados.</li><li><strong>Ámbito y modularidad:</strong> organización ordenada de variables locales y externas dentro del archivo.</li><li><strong>Control de errores:</strong> captura de fallos imprevistos para evitar interrupciones repentinas del programa.</li></ul>",
        apoyo: "https://youtu.be/_6N18g3ewnw?si=LquR-_EO1F_kOUHP"
    },
    {
        id: 2,
        title: "Principios de programación en JavaScript",
        modulo1: "<h3>Módulo 1: Fundamentos y estructura del programa</h3><p>Java es un lenguaje tipado y robusto en el que cada archivo fuente se organiza dentro de clases formales:</p><ul><li><strong>Método de entrada:</strong> el punto de partida donde la máquina virtual inicia la ejecución de cualquier aplicación.</li><li><strong>Tipado estricto:</strong> declaración obligatoria del tipo de dato antes de asignar o modificar un valor.</li><li><strong>Compilación y ejecución:</strong> traducción del código fuente a bytecode ejecutable en cualquier plataforma compatible.</li></ul>",
        modulo2: "<h3>Módulo 2: Programación Orientada a Objetos</h3><p>El núcleo del desarrollo en Java consiste en modelar entidades del mundo real mediante abstracciones de software:</p><ul><li><strong>Clases e instancias:</strong> plantillas maestras que definen la estructura y los ejemplares vivos con estado propio.</li><li><strong>Atributos y métodos:</strong> las características internas del objeto y las acciones concretas que puede realizar.</li><li><strong>Encapsulamiento:</strong> protección de variables internas usando modificadores de acceso y métodos de consulta.</li></ul>",
        modulo3: "<h3>Módulo 3: Manejo de arreglos y excepciones</h3><p>Estructurar colecciones elementales y construir aplicaciones estables ante fallos operativos:</p><ul><li><strong>Arreglos unidimensionales:</strong> conjuntos de tamaño fijo para ordenar variables del mismo tipo de dato.</li><li><strong>Manejo de excepciones:</strong> aislamiento de operaciones críticas dentro de bloques protegidos para prevenir bloqueos.</li><li><strong>Mensajes y depuración:</strong> diagnóstico ordenado de problemas para resolver anomalías durante la ejecución.</li></ul>",
        apoyo: "https://youtu.be/8GTaO9XhA5M?si=o2Am0LVNErBveIBX"
    },
    {
        id: 3,
        title: "Bussiness English",
        modulo1: "<h3>Module 1: Professional Emailing and Writing</h3><p>Written communication in corporate environments requires brevity, clarity, and the right register:</p><ul><li><strong>Subject lines and openings:</strong> craft clear, action-oriented titles paired with respectful professional greetings.</li><li><strong>The core message:</strong> state the main purpose immediately within the opening two sentences.</li><li><strong>Action calls and sign-offs:</strong> define clear next steps, target deadlines, and standard closing remarks.</li></ul>",
        modulo2: "<h3>Module 2: Meetings and Active Participation</h3><p>Effective verbal participation builds credibility and ensures your contributions are heard:</p><ul><li><strong>Interpreting agendas:</strong> prepare talking points around specific topics before entering the conference room.</li><li><strong>Diplomatic interventions:</strong> polite phrases to ask questions, challenge points, or clarify technical terms.</li><li><strong>Summarizing agreements:</strong> restating responsibilities and deliverables before concluding the call.</li></ul>",
        modulo3: "<h3>Module 3: Pitches and Data Presentations</h3><p>Delivering presentations to stakeholders requires smooth signposting and precise numerical language:</p><ul><li><strong>Signposting language:</strong> transitions that guide listeners through beginnings, body points, and conclusions.</li><li><strong>Describing trends:</strong> precise business vocabulary for upward, downward, and stable metrics over time.</li><li><strong>Managing Q&amp;A sessions:</strong> professional strategies to acknowledge, address, or table audience inquiries.</li></ul>",
        apoyo: "https://youtu.be/TJhCKf_qrWI?si=BRWWXY8lF6rMQFrc"
    },
    {
        id: 4,
        title: "Emprende con impacto",
        modulo1: "<h3>Módulo 1: Identificación del problema y propósito</h3><p>Los negocios de impacto resuelven fricciones comunitarias o ambientales mediante propuestas económicamente viables:</p><ul><li><strong>Mapeo de problemas:</strong> observación de necesidades desatendidas en el entorno social o productivo.</li><li><strong>El enfoque de triple impacto:</strong> equilibrio simultáneo entre rentabilidad económica, valor social y cuidado ambiental.</li><li><strong>Propuesta de valor ética:</strong> definición clara del beneficio que el cliente percibe al elegir tu solución.</li></ul>",
        modulo2: "<h3>Módulo 2: Modelo de negocio sostenible</h3><p>Un proyecto necesita una estructura comercial sólida para perdurar en el tiempo sin depender de subsidios:</p><ul><li><strong>Estructura operativa:</strong> actividades clave y recursos indispensables para entregar la solución al usuario.</li><li><strong>Fuentes de ingresos responsables:</strong> canales de venta alineados con la misión del proyecto y precios justos.</li><li><strong>Alianzas locales:</strong> vinculación con actores comunitarios y cadenas de suministro éticas y transparentes.</li></ul>",
        modulo3: "<h3>Módulo 3: Medición del impacto y validación</h3><p>Comprobar la efectividad del proyecto exige métricas tangibles más allá del balance financiero:</p><ul><li><strong>Indicadores sociales y ambientales:</strong> métricas puntuales para evaluar el progreso generado en la comunidad.</li><li><strong>Pilotos y retroalimentación:</strong> pruebas a pequeña escala para ajustar el producto según la respuesta real.</li><li><strong>Estrategias de expansión:</strong> criterios para replicar el modelo en nuevos entornos sin desvirtuar el propósito.</li></ul>",
        apoyo: "https://youtu.be/JffeDI9WqNU?si=dRYg0GHx9UFxr2Rx"
    },
    {
        id: 5,
        title: "Impulso empresarial y emprendimiento",
        modulo1: "<h3>Módulo 1: Validación y Producto Mínimo Viable (MVP)</h3><p>Antes de invertir recursos considerables, es fundamental contrastar las hipótesis iniciales en el mercado:</p><ul><li><strong>El concepto de MVP:</strong> crear la versión más sencilla posible que resuelva la necesidad principal del cliente.</li><li><strong>Entrevistas de validación:</strong> técnicas para escuchar problemas reales sin sesgar la opinión de los usuarios.</li><li><strong>Ajustes basados en evidencia:</strong> refinar características del producto a partir del comportamiento observado.</li></ul>",
        modulo2: "<h3>Módulo 2: Finanzas y estructura de costos</h3><p>La viabilidad de una empresa depende del entendimiento riguroso de sus flujos monetarios y márgenes:</p><ul><li><strong>Costos fijos y variables:</strong> separación de gastos operativos permanentes frente a costos vinculados a la producción.</li><li><strong>Punto de equilibrio:</strong> cálculo del volumen mínimo de ventas requerido para no generar pérdidas.</li><li><strong>Precios y márgenes:</strong> definición de tarifas considerando costos, competencia y valor percibido por el cliente.</li></ul>",
        modulo3: "<h3>Módulo 3: Estrategia comercial y ventas iniciales</h3><p>Generar tracción temprana valida el interés del mercado y proporciona capital para operar:</p><ul><li><strong>Prospección directa:</strong> canales accesibles para contactar a los primeros clientes de forma personalizada.</li><li><strong>Estructuración de ofertas:</strong> presentación clara de beneficios y garantías para cerrar negociaciones iniciales.</li><li><strong>Seguimiento y fidelización:</strong> procesos sencillos para mantener la relación comercial y fomentar la recompra.</li></ul>",
        apoyo: "https://youtu.be/6WwKgBmaTtQ?si=GChkfcjeKCrR2N-4"
    },
    {
        id: 6,
        title: "Publicidad en redes sociales",
        modulo1: "<h3>Módulo 1: Segmentación y perfil del cliente</h3><p>El éxito de una campaña radica en mostrar el mensaje correcto únicamente a quienes tienen interés potencial:</p><ul><li><strong>Definición del público objetivo:</strong> variables demográficas, intereses específicos y patrones de navegación.</li><li><strong>Audiencias personalizadas:</strong> aprovechamiento de bases de datos previas o visitantes de plataformas digitales.</li><li><strong>El viaje del consumidor:</strong> adaptación de anuncios según la etapa de descubrimiento, interés o compra directa.</li></ul>",
        modulo2: "<h3>Módulo 2: Formatos y redacción persuasiva</h3><p>Capturar la atención en pocos segundos requiere creatividad estructurada y mensajes directos:</p><ul><li><strong>Formatos publicitarios:</strong> uso estratégico de imágenes estáticas, carruseles y videos cortos de formato vertical.</li><li><strong>Ganchos visuales:</strong> primeros segundos del anuncio diseñados para detener el desplazamiento continuo en pantalla.</li><li><strong>Llamados a la acción:</strong> indicaciones precisas para dirigir al usuario hacia un formulario, tienda o chat.</li></ul>",
        modulo3: "<h3>Módulo 3: Métricas de rendimiento y optimización</h3><p>Gestionar presupuestos publicitarios exige interpretar datos para tomar decisiones informadas:</p><ul><li><strong>Indicadores clave:</strong> lectura de clics por impresión (CTR), costos por adquisición (CPA) y retornos de inversión.</li><li><strong>Pruebas comparativas:</strong> contraste de variables individuales en anuncios para identificar la versión con mejor desempeño.</li><li><strong>Escalamiento del presupuesto:</strong> criterios para incrementar la inversión en anuncios eficientes sin saturar al público.</li></ul>",
        apoyo: "https://youtu.be/Iky6l5Da9Vo?si=mFYqQBAQ4Zf9PBA-"
    },
    {
        id: 7,
        title: "Excel-de básico a intermedio",
        modulo1: "<h3>Módulo 1: Organización, formato y cálculos elementales</h3><p>La correcta estructuración de hojas de cálculo agiliza el análisis y reduce errores numéricos:</p><ul><li><strong>Navegación y tipos de celda:</strong> diferencias clave entre textos, valores numéricos, porcentajes y fechas.</li><li><strong>Referencias de celda:</strong> utilización de referencias relativas y fijación de rangos con el signo de pesos ($).</li><li><strong>Funciones básicas:</strong> operaciones directas de suma, promedio, conteo y redondeo de series numéricas.</li></ul>",
        modulo2: "<h3>Módulo 2: Fórmulas lógicas y de búsqueda</h3><p>Automatizar revisiones y cruzar información entre diferentes tablas agiliza el trabajo diario:</p><ul><li><strong>Evaluaciones condicionales:</strong> aplicación de reglas lógicas para clasificar registros según valores límite.</li><li><strong>Funciones de búsqueda:</strong> localización de datos vinculados en tablas extensas mediante identificadores clave.</li><li><strong>Tratamiento de texto:</strong> limpieza y estandarización de nombres, correos o códigos alfanuméricos.</li></ul>",
        modulo3: "<h3>Módulo 3: Tablas dinámicas y visualización</h3><p>Transformar filas de información en resúmenes visuales para facilitar la toma de decisiones:</p><ul><li><strong>Creación de tablas dinámicas:</strong> agrupamiento de totales, promedios y porcentajes por categorías en pocos clics.</li><li><strong>Segmentación de datos:</strong> filtros visuales e interactivos para explorar reportes por periodos o sucursales.</li><li><strong>Gráficos estadísticos:</strong> selección del gráfico adecuado (barras, líneas, áreas) según la naturaleza de la información.</li></ul>",
        apoyo: "https://youtu.be/eZPCVg4Jk00?si=Gphyu6UtNYprN5ll"
    },
    {
        id: 8,
        title: "Fundamentos de Power BI",
        modulo1: "<h3>Módulo 1: Extracción y limpieza con Power Query</h3><p>Antes de construir paneles visuales, los datos sin procesar deben ordenarse y estandarizarse:</p><ul><li><strong>Conexión a fuentes:</strong> importación directa desde hojas de cálculo, archivos de texto plano o bases de datos.</li><li><strong>Limpieza de columnas:</strong> eliminación de filas duplicadas, tratamiento de valores nulos y asignación de tipos correctos.</li><li><strong>Transformación de tablas:</strong> anulación de dinamización y combinación de múltiples consultas en una sola.</li></ul>",
        modulo2: "<h3>Módulo 2: Modelado relacional y medidas DAX</h3><p>Un buen modelo dimensional permite realizar consultas complejas sin ralentizar el reporte:</p><ul><li><strong>Relaciones entre tablas:</strong> configuración de cardinalidades (uno a muchos) entre tablas de dimensiones y hechos.</li><li><strong>Columnas calculadas y medidas:</strong> diferencias operativas y de rendimiento entre evaluar fila por fila o en contexto de filtro.</li><li><strong>Funciones esenciales DAX:</strong> cálculos de totales, conteos y filtros dinámicos sobre variables temporales.</li></ul>",
        modulo3: "<h3>Módulo 3: Diseño de dashboards y narrativa visual</h3><p>Presentación ordenada de indicadores clave orientada a usuarios de negocio y directivos:</p><ul><li><strong>Componentes visuales:</strong> distribución estratégica de tarjetas de KPI, matrices y gráficos de evolución temporal.</li><li><strong>Interacción cruzada:</strong> navegación fluida donde la selección en un visual filtra el comportamiento de los demás.</li><li><strong>Buenas prácticas de diseño:</strong> jerarquía tipográfica, uso sobrio del color y orden de lectura intuitivo.</li></ul>",
        apoyo: "https://youtu.be/pwJuFbyhZFE?si=6a9xHHapmpfldW8R"
    },
    {
        id: 9,
        title: "Inglés para entrevistas y networking",
        modulo1: "<h3>Module 1: The STAR Framework</h3><p>Structure compelling answers to behavioral questions without rambling or losing clarity:</p><ul><li><strong>Situation &amp; Task:</strong> outline the background context and define the challenge clearly in 30 seconds.</li><li><strong>Action:</strong> emphasize your direct actions and leadership decisions using dynamic action verbs.</li><li><strong>Result:</strong> quantify the positive outcomes using concrete numbers, efficiency rates, and lessons learned.</li></ul>",
        modulo2: "<h3>Module 2: Elevator Pitch and Career Strengths</h3><p>Introduce yourself concisely and articulate your professional value proposition:</p><ul><li><strong>The 60-second summary:</strong> connect your academic background, core skills, and current career trajectory.</li><li><strong>Highlighting strengths:</strong> present technical abilities and problem-solving examples with natural phrasing.</li><li><strong>Asking relevant questions:</strong> demonstrate curiosity by asking the interviewer insightful questions about team culture.</li></ul>",
        modulo3: "<h3>Module 3: Networking and Professional Follow-ups</h3><p>Build lasting business relationships through thoughtful and polished communications:</p><ul><li><strong>Conversational starters:</strong> easy, respectful ways to open conversations at professional conferences and meetups.</li><li><strong>LinkedIn connection notes:</strong> personalized, brief messages that explain why connecting is mutually valuable.</li><li><strong>Post-interview follow-ups:</strong> send polite thank-you emails reinforcing your excitement for the opportunity within 24 hours.</li></ul>",
        apoyo: "https://youtu.be/CJaMEfU-Jwg?si=-FelXvc8J3z0EsSV"
    },
    {
        id: 10,
        title: "Domina la IA con Gemini",
        modulo1: "<h3>Módulo 1: Ingeniería de prompts efectiva</h3><p>La calidad de las respuestas de un modelo de lenguaje depende de la precisión y estructura de las instrucciones:</p><ul><li><strong>Asignación de roles:</strong> otorgar una perspectiva profesional clara al modelo para ajustar su tono y profundidad.</li><li><strong>Contexto y restricciones:</strong> aportar antecedentes clave y delimitar límites para evitar respuestas ambiguas o extensas.</li><li><strong>Formato de salida:</strong> solicitar resultados organizados en tablas, listas o código directamente aprovechable.</li></ul>",
        modulo2: "<h3>Módulo 2: Capacidades multimodales en acción</h3><p>Aprovechar la capacidad del modelo para analizar diversos tipos de datos en una misma interacción:</p><ul><li><strong>Análisis visual:</strong> interpretación de diagramas, infografías y capturas para extraer datos o resumir esquemas.</li><li><strong>Procesamiento de documentos:</strong> síntesis de textos extensos y extracción de puntos clave sin perder datos críticos.</li><li><strong>Asistencia técnica:</strong> revisión y depuración de código, proponiendo mejoras de rendimiento y legibilidad.</li></ul>",
        modulo3: "<h3>Módulo 3: Flujos de productividad diaria</h3><p>Integrar la inteligencia artificial como herramienta de apoyo para agilizar tareas recurrentes:</p><ul><li><strong>Redacción y refinamiento:</strong> generación rápida de borradores para comunicados, minutas y propuestas.</li><li><strong>Estructuración de ideas:</strong> lluvia de opciones categorizadas para resolver problemas o planificar calendarios de trabajo.</li><li><strong>Validación crítica:</strong> verificación de consistencia en textos generados para asegurar rigor y precisión antes de utilizarlos.</li></ul>",
        apoyo: "https://youtu.be/Zh-WpcNjSdY?si=wC0IB7kG86qHFva2"
    },
    {
        id: 11,
        title: "Fundamentos de marketing digital",
        modulo1: "<h3>Módulo 1: Estrategia y embudos de conversión</h3><p>Una presencia digital efectiva guía al usuario desde el descubrimiento inicial hasta la fidelización recurrente:</p><ul><li><strong>Fases del embudo:</strong> diferenciar tácticas dirigidas a dar a conocer una marca de aquellas pensadas para cerrar ventas.</li><li><strong>Definición del público:</strong> identificación de las necesidades, problemas y hábitos de consulta del cliente meta.</li><li><strong>Selección de canales:</strong> elegir las plataformas idóneas según el tipo de producto y los hábitos de la audiencia.</li></ul>",
        modulo2: "<h3>Módulo 2: Contenido, SEO y canales de retención</h3><p>El posicionamiento orgánico y la comunicación directa permiten construir audiencias duraderas:</p><ul><li><strong>Marketing de contenidos:</strong> creación de piezas informativas que respondan a dudas reales del consumidor.</li><li><strong>Fundamentos de SEO:</strong> uso de palabras clave y estructura técnica para facilitar la indexación en motores de búsqueda.</li><li><strong>Email marketing:</strong> diseño de campañas automatizadas para mantener informada y comprometida a la comunidad.</li></ul>",
        modulo3: "<h3>Módulo 3: Métricas y análisis de desempeño</h3><p>Medir el impacto de cada acción garantiza que el presupuesto se asigne a las estrategias más rentables:</p><ul><li><strong>Tráfico y comportamiento:</strong> seguimiento de páginas visitadas, tiempos de permanencia y porcentaje de rebote.</li><li><strong>Tasa de conversión:</strong> porcentaje de usuarios que completan acciones clave, como suscripciones o compras.</li><li><strong>Rentabilidad por cliente:</strong> relación entre lo invertido para captar un nuevo usuario y su valor financiero en el tiempo.</li></ul>",
        apoyo: "https://youtu.be/Ctd6BTuZmjA?si=B9z3VBHmxhsj3tJC"
    },
    {
        id: 12,
        title: "Leadership",
        modulo1: "<h3>Módulo 1: Autoliderazgo y gestión personal</h3><p>Liderar a otros empieza por la autorregulación, la claridad de prioridades y el manejo del propio tiempo:</p><ul><li><strong>Inteligencia emocional:</strong> reconocimiento de emociones y manejo de la compostura bajo situaciones de presión.</li><li><strong>Organización del tiempo:</strong> priorización de actividades estratégicas frente a urgencias operativas inmediatas.</li><li><strong>Coherencia y valores:</strong> actuar de forma predecible y transparente para construir confianza en el entorno laboral.</li></ul>",
        modulo2: "<h3>Módulo 2: Comunicación asertiva y retroalimentación</h3><p>Mantener alineado al equipo requiere mensajes claros y espacios constructivos para evaluar el desempeño:</p><ul><li><strong>Escucha activa:</strong> prestar atención total a los integrantes del equipo para comprender inquietudes de fondo.</li><li><strong>Cultura de feedback:</strong> entregar observaciones centradas en hechos medibles y conductas, no en juicios personales.</li><li><strong>Manejo de diferencias:</strong> mediar desacuerdos buscando acuerdos operativos que mantengan la cohesión del grupo.</li></ul>",
        modulo3: "<h3>Módulo 3: Desarrollo de personas y delegación</h3><p>Un liderazgo sostenible potencia las habilidades individuales y distribuye la toma de decisiones:</p><ul><li><strong>Delegación responsable:</strong> transferir autoridad y objetivos claros en lugar de limitarse a repartir tareas rutinarias.</li><li><strong>Identificación del potencial:</strong> reconocer las fortalezas particulares de cada integrante para asignar retos adecuados.</li><li><strong>Rendición de cuentas:</strong> establecer métricas y fechas compartidas para evaluar avances sin recurrir a la microgestión.</li></ul>",
        apoyo: "https://youtu.be/dv8LdkjOpjU?si=au1XzkkL_hXrRwAC"
    }
];
       